{% set name = "Werkzeug" %}
{% set version = "0.11.15" %}
{% set hash_type = "sha256" %}
{% set hash = "455d7798ac263266dbd38d4841f7534dd35ca9c3da4a8df303f8488f38f3bcc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug
    - werkzeug.contrib

about:
  home: http://werkzeug.pocoo.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: The Python WSGI Utility Library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.

extra:
  recipe-maintainers:
    - goanpeca
    - mathieu1
